### ISSUE TITLE
spinning animation

### ISSUE THREAD

**Issue by Jaspervv** [iconify-design/iconify#6]
Does Iconify come with a way to make an icon actively spin? If not then it might be worth considering.

I'm migrating one of our sites to Iconify, one of the most occurring icons is a spinning `mdi-loading`, using just materialdesignicons you would achieve it with `mdi-spin`:
```html
<span class='mdi mdi-loading mdi-spin'></span>
```

My current implementation with Iconify is the following, which of course is fine on it's own:
```css
.spin {
  animation-name: spin;
  animation-duration: 2000ms;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}
@keyframes spin {
  from {
    transform:rotate(0deg);
  }
  to {
    transform:rotate(360deg);
  }
}
```
